# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 11, 14, 56, 380002, tzinfo=utc)),
        ),
    ]
