# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170728_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterAccount',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 11, 53, 58, 130278, tzinfo=utc)),
        ),
    ]
