# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170804_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 14, 18, 41, 808847, tzinfo=utc)),
        ),
    ]
