# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170804_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 6, 1, 25, 745895)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 6, 1, 25, 744394)),
        ),
    ]
