# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170805_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 10, 11, 11, 935530)),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_pic',
            field=models.ImageField(default='media/no-img.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 10, 11, 11, 935530)),
        ),
    ]
