# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170805_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 10, 28, 42, 454095)),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_pic',
            field=models.ImageField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 10, 28, 42, 450092)),
        ),
    ]
