# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170805_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 11, 31, 12, 432738)),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_pic',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 11, 31, 12, 430737)),
        ),
    ]
