# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170806_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 6, 11, 5, 7, 570930)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 6, 11, 5, 7, 555305)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
