# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20170807_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_cover_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 2, 16, 5, 391992)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 2, 16, 5, 390990)),
        ),
    ]
