# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20170815_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 2, 25, 44, 547147)),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_pic',
            field=models.FileField(upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 2, 25, 44, 545158)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
