# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20170818_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 14, 51, 48, 195159)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 14, 51, 48, 193658)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
