# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20170821_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 22, 20, 52, 58, 904960)),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_pic',
            field=models.ImageField(upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 22, 20, 52, 58, 902959)),
        ),
    ]
