# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20170824_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 3, 19, 42, 214621)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 3, 19, 42, 214621)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edit_status',
            field=models.BooleanField(),
        ),
    ]
