# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20170824_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 3, 24, 33, 454293)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 3, 24, 33, 454293)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edit_status',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
