# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20170905_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hmm',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 21, 12, 22, 941339)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 21, 12, 22, 939753)),
        ),
    ]
