# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20170905_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 15, 27, 16, 41436)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 15, 27, 16, 39865)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_cover_pic',
            field=models.ImageField(null=True, upload_to='user/cover/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile_pic',
            field=models.ImageField(null=True, upload_to='user/profile/'),
        ),
    ]
