# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:42
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_auto_20170906_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_cover_pic',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/mi-kill/my-first-blog/staticfiles'), upload_to='user/cover/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile_pic',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/mi-kill/my-first-blog/staticfiles'), upload_to='user/profile/'),
        ),
    ]
