# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_auto_20170906_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_cover_pic',
            field=models.ImageField(null=True, upload_to='user/cover/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile_pic',
            field=models.ImageField(null=True, upload_to='user/profile/'),
        ),
    ]
